CREATE TABLE public.person(
	person_id SERIAL PRIMARY KEY,
	person_age int NOT NULL,
	person_birthday date NULL,
	person_document_cpf varchar(255) NOT NULL,
	person_document_rg varchar(255) NULL,
	person_email varchar(255) NOT NULL,
	person_last_update timestamp NULL,
	person_name varchar(255) NOT NULL,
	person_register_date timestamp NOT NULL,
	person_sex varchar(255) NOT NULL,
	person_status bool NOT NULL
);

CREATE TABLE public.person_address(
	address_id SERIAL PRIMARY KEY,
	city varchar(255) NOT NULL,
	complement varchar(255) NULL,
	district varchar(255) NOT NULL,
	"number" varchar(255) NOT NULL,
	postal_code int NOT NULL,
	"state" int NULL,
	street varchar(255) NULL,
	person_id SERIAL NOT null,
	foreign key (person_id) references person (person_id)
);

CREATE TABLE public.person_doctor (
	medical_especiality varchar(255) NOT NULL,
	professional_register_number int NOT NULL,
	professional_register_state varchar(255) NOT NULL,
	professional_register_validity date NOT NULL,
	person_id SERIAL PRIMARY KEY,
	foreign key (person_id) references person (person_id)
);

CREATE TABLE public.person_doctor_hour_friday (
	doctor_hour_friday_id SERIAL PRIMARY KEY,
	a1400 bool NOT NULL,
	a1430 bool NOT NULL,
	a1500 bool NOT NULL,
	a1530 bool NOT NULL,
	a1600 bool NOT NULL,
	a1630 bool NOT NULL,
	a1700 bool NOT NULL,
	a1730 bool NOT NULL,
	doctor_name varchar(255) NOT NULL,
	m0800 bool NOT NULL,
	m0830 bool NOT NULL,
	m0900 bool NOT NULL,
	m0930 bool NOT NULL,
	m1000 bool NOT NULL,
	m1030 bool NOT NULL,
	m1100 bool NOT NULL,
	m1130 bool NOT NULL,
	medical_especiality varchar(255) NOT NULL,
	n1800 bool NOT NULL,
	n1830 bool NOT NULL,
	n1900 bool NOT NULL,
	n1930 bool NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	CONSTRAINT person_doctor_hour_friday_pkey PRIMARY KEY (doctor_hour_friday_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);

CREATE TABLE public.person_doctor_hour_monday (
	doctor_hour_monday_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	a1400 bool NOT NULL,
	a1430 bool NOT NULL,
	a1500 bool NOT NULL,
	a1530 bool NOT NULL,
	a1600 bool NOT NULL,
	a1630 bool NOT NULL,
	a1700 bool NOT NULL,
	a1730 bool NOT NULL,
	doctor_name varchar(255) NOT NULL,
	m0800 bool NOT NULL,
	m0830 bool NOT NULL,
	m0900 bool NOT NULL,
	m0930 bool NOT NULL,
	m1000 bool NOT NULL,
	m1030 bool NOT NULL,
	m1100 bool NOT NULL,
	m1130 bool NOT NULL,
	medical_especiality varchar(255) NOT NULL,
	n1800 bool NOT NULL,
	n1830 bool NOT NULL,
	n1900 bool NOT NULL,
	n1930 bool NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	CONSTRAINT person_doctor_hour_monday_pkey PRIMARY KEY (doctor_hour_monday_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);

CREATE TABLE public.person_doctor_hour_saturday (
	doctor_hour_saturday_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	doctor_name varchar(255) NOT NULL,
	m0800 bool NOT NULL,
	m0830 bool NOT NULL,
	m0900 bool NOT NULL,
	m0930 bool NOT NULL,
	m1000 bool NOT NULL,
	m1030 bool NOT NULL,
	m1100 bool NOT NULL,
	m1130 bool NOT NULL,
	medical_especiality varchar(255) NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	CONSTRAINT person_doctor_hour_saturday_pkey PRIMARY KEY (doctor_hour_saturday_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);

CREATE TABLE public.person_doctor_hour_thursday (
	doctor_hour_thursday_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	a1400 bool NOT NULL,
	a1430 bool NOT NULL,
	a1500 bool NOT NULL,
	a1530 bool NOT NULL,
	a1600 bool NOT NULL,
	a1630 bool NOT NULL,
	a1700 bool NOT NULL,
	a1730 bool NOT NULL,
	doctor_name varchar(255) NOT NULL,
	m0800 bool NOT NULL,
	m0830 bool NOT NULL,
	m0900 bool NOT NULL,
	m0930 bool NOT NULL,
	m1000 bool NOT NULL,
	m1030 bool NOT NULL,
	m1100 bool NOT NULL,
	m1130 bool NOT NULL,
	medical_especiality varchar(255) NOT NULL,
	n1800 bool NOT NULL,
	n1830 bool NOT NULL,
	n1900 bool NOT NULL,
	n1930 bool NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	CONSTRAINT person_doctor_hour_thursday_pkey PRIMARY KEY (doctor_hour_thursday_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);

CREATE TABLE public.person_doctor_hour_tuesday (
	doctor_hour_tuesday_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	a1400 bool NOT NULL,
	a1430 bool NOT NULL,
	a1500 bool NOT NULL,
	a1530 bool NOT NULL,
	a1600 bool NOT NULL,
	a1630 bool NOT NULL,
	a1700 bool NOT NULL,
	a1730 bool NOT NULL,
	doctor_name varchar(255) NOT NULL,
	m0800 bool NOT NULL,
	m0830 bool NOT NULL,
	m0900 bool NOT NULL,
	m0930 bool NOT NULL,
	m1000 bool NOT NULL,
	m1030 bool NOT NULL,
	m1100 bool NOT NULL,
	m1130 bool NOT NULL,
	medical_especiality varchar(255) NOT NULL,
	n1800 bool NOT NULL,
	n1830 bool NOT NULL,
	n1900 bool NOT NULL,
	n1930 bool NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	CONSTRAINT person_doctor_hour_tuesday_pkey PRIMARY KEY (doctor_hour_tuesday_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);

CREATE TABLE public.person_doctor_hour_wednesday (
	doctor_hour_wednesday_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	a1400 bool NOT NULL,
	a1430 bool NOT NULL,
	a1500 bool NOT NULL,
	a1530 bool NOT NULL,
	a1600 bool NOT NULL,
	a1630 bool NOT NULL,
	a1700 bool NOT NULL,
	a1730 bool NOT NULL,
	doctor_name varchar(255) NOT NULL,
	m0800 bool NOT NULL,
	m0830 bool NOT NULL,
	m0900 bool NOT NULL,
	m0930 bool NOT NULL,
	m1000 bool NOT NULL,
	m1030 bool NOT NULL,
	m1100 bool NOT NULL,
	m1130 bool NOT NULL,
	medical_especiality varchar(255) NOT NULL,
	n1800 bool NOT NULL,
	n1830 bool NOT NULL,
	n1900 bool NOT NULL,
	n1930 bool NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	CONSTRAINT person_doctor_hour_wednesday_pkey PRIMARY KEY (doctor_hour_wednesday_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);

CREATE TABLE public.person_employee (
	admission_date varchar(255) NULL,
	funcionary_id SERIAL NOT NULL,
	institucional_email varchar(255) NULL,
	"role" varchar(255) NULL,
	person_id int8 NOT NULL,
	CONSTRAINT person_employee_pkey PRIMARY KEY (person_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.person(person_id)
);

CREATE TABLE public.person_pacient (
	person_id SERIAL NOT NULL,
	health_insurance_health_insurance_id SERIAL NULL,
	CONSTRAINT person_pacient_pkey PRIMARY KEY (person_id),
	CONSTRAINT fk_health_insurance_id FOREIGN KEY (health_insurance_health_insurance_id) REFERENCES public.person_pacient_health_insurance(health_insurance_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.person(person_id)
);

CREATE TABLE public.person_pacient_child (
	child_id SERIAL PRIMARY KEY,
	child_age int NOT NULL,
	child_birthday date NOT NULL,
	child_name varchar(255) NOT NULL,
	child_sex varchar(255) NOT NULL,
	last_update timestamp NULL,
	printed_term bool NOT NULL,
	register_date timestamp NOT NULL,
	person_id SERIAL NULL,
	CONSTRAINT person_pacient_child_pkey PRIMARY KEY (child_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.person_pacient(person_id)
);

CREATE TABLE public.person_pacient_health_insurance (
	health_insurance_id SERIAL PRIMARY KEY,
	coverage varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"number" int NOT NULL,
	person_last_update timestamp NULL,
	person_register_date timestamp NOT NULL,
	person_id SERIAL NOT NULL,
	CONSTRAINT person_pacient_health_insurance_pkey PRIMARY KEY (health_insurance_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.person_pacient(person_id)
);

CREATE TABLE public.person_pacient_prontuary (
	prontuary_id SERIAL PRIMARY KEY,
	first_time bool NOT NULL,
	last_update timestamp NULL,
	register_date timestamp NOT NULL,
	symptoms varchar(255) NOT NULL,
	person_id SERIAL NOT NULL,
	CONSTRAINT person_pacient_prontuary_pkey PRIMARY KEY (prontuary_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.person_pacient(person_id)
);

CREATE TABLE public.person_phone (
	phone_id SERIAL PRIMARY KEY,
	"number" int NOT NULL,
	person_phone_name varchar(80) NULL,
	"type" VARCHAR(255) NOT NULL,
	person_id SERIAL NOT NULL,
	CONSTRAINT person_phone_pkey PRIMARY KEY (phone_id),
	CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES public.person(person_id)
);

CREATE TABLE public.consult (
	consult_id SERIAL PRIMARY KEY,
	consult_date_request varchar(255) NOT NULL,
	consult_especiality varchar(255) NOT NULL,
	consult_hour_request varchar(255) NOT NULL,
	person_id SERIAL NOT NULL,
	register_date timestamp NOT NULL,
	"status" varchar(255) NOT NULL,
	person_doctor_person_id SERIAL NOT NULL,
	person_pacient_person_id SERIAL NOT NULL,
	CONSTRAINT consult_pkey PRIMARY KEY (consult_id),
	CONSTRAINT fk_pacient_id FOREIGN KEY (person_pacient_person_id) REFERENCES public.person_pacient(person_id),
	CONSTRAINT fk_doctor_id FOREIGN KEY (person_doctor_person_id) REFERENCES public.person_doctor(person_id)
);